### ISSUE TITLE
<bug> Shadow elements layered above parent container content.

### ISSUE THREAD

**Issue by azariah001** [Polymer/paper-shadow#18]
I encountered this issue while constructing my resume in HTML last week. I was obviously using the paper-shadow for embellishing and grouping topics but.... I quickly discovered that when the paper -shadows were intilaized on objects I wasn't able to select text or click on links inside the container elements. In the end I resorted to manually adding a CSS rule for each type of tag that I required to be  accessible.

For instance.

``` css
    div.card > p {
        position: relative;
        z-index: 1;
    }
```

Fixed the issue but it would be great not to have to use CSS to fix an eccentricity of the paper-shadow scripts. Especially as new users are left scratching there heads like I was.
